spring.application.name=pilates-booking-api

spring.datasource.url=jdbc:postgresql://localhost:5432/pilates_db
spring.datasource.username=admin
spring.datasource.password=adminpassword
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect