spring.application.name=pilates-booking-api

spring.datasource.url=jdbc:postgresql://192.168.0.34:5432/pilates_db
spring.datasource.username=postgres
spring.datasource.password=adminpassword1
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true